import React, { useState, useEffect, useRef } from 'react';

interface Agent {
  id: number;
  agentCode: string;
  agentName: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  rank: string;
  introducerCode: string | null;
  joiningDate: string;
  status: boolean;
  accountNumber: string;
  bankName: string;
  ifscCode: string;
  panNumber: string;
  createdAt: number;
  updatedAt: number;
}

const defaultNewAgent: Omit<Agent, 'id' | 'createdAt' | 'updatedAt'> = {
  agentCode: '',
  agentName: '',
  email: '',
  phone: '',
  address: '',
  city: '',
  state: '',
  pincode: '',
  rank: 'Agent',
  introducerCode: null,
  joiningDate: new Date().toISOString().split('T')[0],
  status: true,
  accountNumber: '',
  bankName: '',
  ifscCode: '',
  panNumber: '',
};

interface AgentFormProps {
  initialAgentData?: Partial<Agent>;
  isEditing: boolean;
  onSave: (agent: Agent) => void;
  onCancel: () => void;
  showFlashMessage: (type: 'success' | 'error', message: string) => void;
  existingAgentCodes: string[];
  existingPanNumbers: string[];
  loading: boolean;
}

const rankOptions = ['Junior Agent', 'Agent', 'Senior Agent', 'Partner', 'Manager'];

const generateUniqueAgentCode = (existingCodes: string[], prefix: string = 'PTR-'): string => {
  let newCode: string;
  let isUnique = false;
  let attempts = 0;
  do {
    newCode = prefix + Math.random().toString(36).substring(2, 8).toUpperCase();
    isUnique = !existingCodes.includes(newCode);
    attempts++;
    if (attempts > 1000) return '';
  } while (!isUnique);
  return newCode;
};

const AgentForm: React.FC<AgentFormProps> = ({
  initialAgentData,
  isEditing,
  onSave,
  onCancel,
  showFlashMessage,
  existingAgentCodes,
  existingPanNumbers,
  loading,
}) => {
  const [formData, setFormData] = useState<Partial<Agent>>(() =>
    initialAgentData ? { ...defaultNewAgent, ...initialAgentData } : defaultNewAgent
  );

  const hasAutoGeneratedCodeRef = useRef(false);

  useEffect(() => {
    setFormData(initialAgentData ? { ...defaultNewAgent, ...initialAgentData } : defaultNewAgent);
    hasAutoGeneratedCodeRef.current = false;
  }, [initialAgentData, isEditing]);

  useEffect(() => {
    if (!isEditing && !formData.agentCode && !hasAutoGeneratedCodeRef.current) {
      const generatedCode = generateUniqueAgentCode(existingAgentCodes);
      if (generatedCode) {
        setFormData((prev) => ({ ...prev, agentCode: generatedCode }));
        hasAutoGeneratedCodeRef.current = true;
      }
    }
  }, [isEditing, formData.agentCode, existingAgentCodes]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { id, value, type, checked } = e.target as HTMLInputElement;
    setFormData((prev) => ({
      ...prev,
      [id]: type === 'checkbox' ? checked : value,
    }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const requiredFields: Array<keyof Agent> = [
      'agentCode', 'agentName', 'email', 'phone', 'address', 'city', 'state', 'pincode',
      'rank', 'joiningDate', 'accountNumber', 'bankName', 'ifscCode', 'panNumber'
    ];
    for (const field of requiredFields) {
      if (!formData[field] || String(formData[field]).trim() === '') {
        showFlashMessage('error', `Mandatory field "${field}" is required.`);
        return;
      }
    }
    
    // PAN Uniqueness Check
    const panToVerify = formData.panNumber?.trim().toUpperCase();
    if (panToVerify) {
      const isNewPan = !isEditing || (isEditing && panToVerify !== initialAgentData?.panNumber?.toUpperCase());
      if (isNewPan && existingPanNumbers.map(p => p.toUpperCase()).includes(panToVerify)) {
        showFlashMessage('error', `Duplicate Error: PAN "${panToVerify}" is already registered.`);
        return;
      }
    }

    const agentToSave: Agent = {
      ...defaultNewAgent,
      ...formData,
      id: formData.id || Date.now(),
      createdAt: formData.createdAt || Date.now(),
      updatedAt: Date.now(),
    } as Agent;

    onSave(agentToSave);
  };

  const inputClasses = "w-full bg-white border border-slate-300 rounded-xl py-4 px-5 text-lg font-semibold text-slate-950 focus:ring-4 focus:ring-primary/5 focus:border-primary outline-none transition-all placeholder-slate-400";

  return (
    <div className="p-10 space-y-10 bg-white rounded-[32px] shadow-card border border-slate-100 animate-fade-in">
      <div className="flex justify-between items-center border-b border-slate-100 pb-6">
        <h2 className="text-3xl font-black text-slate-900 tracking-tight">
          {isEditing ? 'Modify Partner Profile' : 'Enroll New Partner'}
        </h2>
        <span className="text-xs font-black uppercase tracking-widest text-slate-400 bg-slate-50 px-4 py-2 rounded-full">Manual Entry</span>
      </div>
      
      <form onSubmit={handleSubmit} className="space-y-10">
        <fieldset className="bg-slate-50/50 border border-slate-100 rounded-2xl p-8">
          <legend className="text-sm font-black text-primary uppercase tracking-widest px-4">Identity & Personal Details</legend>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-6">
            <div>
              <label className="block text-slate-700 text-sm font-bold mb-2 ml-1">Partner Code</label>
              <input
                type="text"
                id="agentCode"
                className={`${inputClasses} bg-slate-100 cursor-not-allowed`}
                value={formData.agentCode || ''}
                readOnly
              />
            </div>
            <div>
              <label className="block text-slate-700 text-sm font-bold mb-2 ml-1">Full Name *</label>
              <input
                type="text"
                id="agentName"
                className={inputClasses}
                placeholder="Ex: John Doe"
                value={formData.agentName || ''}
                onChange={handleChange}
                required
              />
            </div>
            <div>
              <label className="block text-slate-700 text-sm font-bold mb-2 ml-1">Designated Rank</label>
              <select
                id="rank"
                className={inputClasses}
                value={formData.rank || ''}
                onChange={handleChange}
              >
                {rankOptions.map((opt) => <option key={opt} value={opt}>{opt}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-slate-700 text-sm font-bold mb-2 ml-1">Joining Date</label>
              <input
                type="date"
                id="joiningDate"
                className={inputClasses}
                value={formData.joiningDate || ''}
                onChange={handleChange}
              />
            </div>
          </div>
        </fieldset>

        <fieldset className="bg-slate-50/50 border border-slate-100 rounded-2xl p-8">
          <legend className="text-sm font-black text-primary uppercase tracking-widest px-4">Contact & Communication</legend>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-6">
            <div>
              <label className="block text-slate-700 text-sm font-bold mb-2 ml-1">Mobile No *</label>
              <input
                type="tel"
                id="phone"
                className={inputClasses}
                placeholder="+91 00000 00000"
                value={formData.phone || ''}
                onChange={handleChange}
                required
              />
            </div>
            <div>
              <label className="block text-slate-700 text-sm font-bold mb-2 ml-1">Email Address *</label>
              <input
                type="email"
                id="email"
                className={inputClasses}
                placeholder="name@agency.com"
                value={formData.email || ''}
                onChange={handleChange}
                required
              />
            </div>
            <div className="md:col-span-2">
              <label className="block text-slate-700 text-sm font-bold mb-2 ml-1">Permanent Address</label>
              <textarea
                id="address"
                rows={3}
                className={`${inputClasses} resize-none`}
                placeholder="Full Street Address..."
                value={formData.address || ''}
                onChange={handleChange}
                required
              />
            </div>
            <div className="grid grid-cols-3 md:col-span-2 gap-6">
              <input type="text" id="city" className={inputClasses} placeholder="City" value={formData.city || ''} onChange={handleChange} required />
              <input type="text" id="state" className={inputClasses} placeholder="State" value={formData.state || ''} onChange={handleChange} required />
              <input type="text" id="pincode" className={inputClasses} placeholder="Pincode" value={formData.pincode || ''} onChange={handleChange} required />
            </div>
          </div>
        </fieldset>

        <fieldset className="bg-slate-50/50 border border-slate-100 rounded-2xl p-8">
          <legend className="text-sm font-black text-primary uppercase tracking-widest px-4">Compliance & Settlement</legend>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-6">
            <div>
              <label className="block text-slate-700 text-sm font-bold mb-2 ml-1">PAN Number *</label>
              <input
                type="text"
                id="panNumber"
                className={`${inputClasses} uppercase tracking-widest`}
                placeholder="ABCDE1234F"
                value={formData.panNumber || ''}
                onChange={handleChange}
                required
              />
            </div>
            <div>
              <label className="block text-slate-700 text-sm font-bold mb-2 ml-1">Bank Account No.</label>
              <input
                type="text"
                id="accountNumber"
                className={inputClasses}
                placeholder="000000000000"
                value={formData.accountNumber || ''}
                onChange={handleChange}
                required
              />
            </div>
            <div>
              <label className="block text-slate-700 text-sm font-bold mb-2 ml-1">IFSC Code</label>
              <input
                type="text"
                id="ifscCode"
                className={`${inputClasses} uppercase`}
                placeholder="SBIN0001234"
                value={formData.ifscCode || ''}
                onChange={handleChange}
                required
              />
            </div>
            <div>
              <label className="block text-slate-700 text-sm font-bold mb-2 ml-1">Bank Name</label>
              <input
                type="text"
                id="bankName"
                className={inputClasses}
                placeholder="Ex: State Bank of India"
                value={formData.bankName || ''}
                onChange={handleChange}
                required
              />
            </div>
          </div>
        </fieldset>

        <div className="flex justify-end items-center gap-6 pt-10 border-t border-slate-100">
          <button 
            type="button" 
            onClick={onCancel} 
            className="px-10 py-4 text-slate-500 font-bold hover:text-slate-900 transition-colors"
          >
            Discard Changes
          </button>
          <button 
            type="submit" 
            className="px-16 py-4 bg-primary text-white rounded-[20px] font-black text-lg hover:bg-primary-dark transition-all shadow-lg shadow-primary/20 active:scale-95 disabled:opacity-50" 
            disabled={loading}
          >
            {loading ? 'Processing...' : (isEditing ? 'Commit Updates' : 'Confirm Enrollment')}
          </button>
        </div>
      </form>
    </div>
  );
};

export default AgentForm;